import Mathlib
import TauCeti.AlgebraicTopology.SimplicialComplex.Realization
import TauCeti.Topology.JordanCurve.Basic
import TauCeti.Topology.Triangulable

/-!
# Surface topology, finite presentations, and classification: target signatures

**This file is not the roadmap and is not exhaustive.** The definitive document is
`README.md`. The declarations here suggest Lean forms for load-bearing objects and
particular milestones, so that contributors and reviewers converge on names and
signatures; discharging all of them finishes neither a layer nor the roadmap. `sorry` is
allowed in this human-owned roadmap library: these are targets, not completed proofs.

This roadmap deliberately chooses two-dimensional generalized maps as the finite hub.
Oriented maps, hypermaps, cellulations, and polygonal schemas are presentations of the
same finite surface data; realization, Euler characteristic, orientability, and the main
operations are defined at the hub and compared to the other presentations. The core
layers culminate in classification; mapping class groups and planarity are substantial
follow-on layers.

The file therefore pins more object-level vocabulary than many roadmaps do. Where the
README itself marks a definition as unresolved -- most importantly the exact local
nondegeneracy condition characterizing surface generalized maps -- this file does **not**
replace it by `Prop := sorry`. Such conditions remain comments until they can be stated
honestly. Likewise, graph-facing targets remain schematic until the current multigraph
API has been verified, as required by the roadmap.
-/

noncomputable section

namespace TauCetiRoadmap.SurfaceTopology

open Function Set

universe u v w

/-! ## Layer 0: finite conventions -/

/-- A finite cyclic word with repeated labels, modulo cyclic rotation. The implementation
should remain separate from `CircularOrder` and from the topological circle. -/
def CyclicWord (α : Type u) : Type u :=
  sorry

/-- A bundled finite indexing type. Moves which add or remove cells must not pretend to
live on a fixed ambient type. -/
structure BundledFinite where
  ι : Type u
  fintype : Fintype ι
  decEq : DecidableEq ι

/-!
The isomorphism closure used by move relations should be compiled once the concrete
bundled object is known. The important constraint is that `Relation.ReflTransGen` is
applied *after* closing the elementary relation under isomorphism of the bundled index
type; Pachner/schema moves change that type.
-/

/-! ## Layer 1: generalized maps -/

/-- An `n`-dimensional generalized map: `n+1` involutions, with non-neighbouring
involutions commuting. This definition is dimension-polymorphic even though the roadmap
only develops the two-dimensional theory. -/
structure GMap (n : ℕ) (D : Type u) [Fintype D] [DecidableEq D] where
  adj : Fin (n + 1) → Equiv.Perm D
  involutive : ∀ i, Function.Involutive (adj i)
  commute_of_far : ∀ i j, i.1 + 2 ≤ j.1 → Function.Commute (adj i) (adj j)

abbrev GMap2 (D : Type u) [Fintype D] [DecidableEq D] := GMap 2 D

/-- The `i`-cells are the orbits generated by all adjacencies except `αᵢ`.
The implementation should use Mathlib's orbit/subgroup machinery rather than a private
reachability relation. -/
noncomputable def GMap.Cell {n : ℕ} {D : Type u} [Fintype D] [DecidableEq D]
    (G : GMap n D) (i : Fin (n + 1)) : Type u :=
  sorry

/-- Cells of a finite generalized map are finite orbit quotients. -/
noncomputable instance GMap.instFiniteCell {n : ℕ} {D : Type u}
    [Fintype D] [DecidableEq D] (G : GMap n D) (i : Fin (n + 1)) :
    Finite (G.Cell i) :=
  sorry

/-- Isomorphism of two-dimensional generalized maps, allowing the dart type to change. -/
structure GMap2.Iso {D : Type u} {D' : Type v}
    [Fintype D] [DecidableEq D] [Fintype D'] [DecidableEq D']
    (G : GMap2 D) (G' : GMap2 D') where
  toEquiv : D ≃ D'
  map_adj : ∀ i d, toEquiv (G.adj i d) = G'.adj i (toEquiv d)

/-- Euler characteristic from orbit cells. -/
def GMap2.eulerChar {D : Type u} [Fintype D] [DecidableEq D] (G : GMap2 D) : ℤ :=
  (Nat.card (G.Cell 0) : ℤ) - Nat.card (G.Cell 1) + Nat.card (G.Cell 2)

/-- A boundary dart is a fixed point of the highest-order involution. -/
def GMap2.IsBoundaryDart {D : Type u} [Fintype D] [DecidableEq D]
    (G : GMap2 D) (d : D) : Prop :=
  G.adj 2 d = d

/-- Orientability as bipartiteness of the dart-adjacency graph, ignoring fixed
adjacencies representing boundary. -/
def GMap2.IsOrientable {D : Type u} [Fintype D] [DecidableEq D] (G : GMap2 D) : Prop :=
  ∃ S : Set D, ∀ i d, G.adj i d ≠ d → (d ∈ S ↔ G.adj i d ∉ S)

/-- A chosen orientation is extra data; `IsOrientable` is only the existence property. -/
structure GMap2.Orientation {D : Type u} [Fintype D] [DecidableEq D] (G : GMap2 D) where
  side : Set D
  flips : ∀ i d, G.adj i d ≠ d → (d ∈ side ↔ G.adj i d ∉ side)

/-- A generalized map with its finite dart type bundled. This is the codomain of moves
which change the number or type of darts. -/
structure BundledGMap2 where
  D : Type u
  fintypeD : Fintype D
  decEqD : DecidableEq D
  map : @GMap 2 D fintypeD decEqD

/-!
**Do not compile `IsSurfaceGMap` yet as a placeholder proposition.** The exact finite
local nondegeneracy condition is the highest-risk definition in the roadmap. It must be
settled against Damiand--Lienhardt, must admit one-cell presentations such as the
projective-plane word `aa`, and must be proved equivalent to the realization having only
disc or half-disc neighbourhoods. Once pinned, add:

  def IsSurfaceGMap (G : GMap2 D) : Prop :=
    (∀ d, G.adj 0 d ≠ d) ∧ (∀ d, G.adj 1 d ≠ d) ∧ <exact local condition>

  def IsClosedSurfaceGMap (G : GMap2 D) : Prop :=
    IsSurfaceGMap G ∧ ∀ d, G.adj 2 d ≠ d

and the boundary-component count, connectedness API, and orientable/nonorientable genus
formulas. The explicit sphere/projective-plane/torus/Klein-bottle/disc/annulus/Möbius
examples belong in the implementation as decidable tests of this definition.
-/

/-! ## Layer 2: presentations and comparison theorems -/

/-- An oriented combinatorial map / rotation system. -/
structure CombinatorialMap (D : Type u) [Fintype D] [DecidableEq D] where
  sigma : Equiv.Perm D
  alpha : Equiv.Perm D
  alpha_involutive : Function.Involutive alpha
  alpha_free : ∀ d, alpha d ≠ d

/-- Passing from an oriented map to the unoriented generalized-map hub doubles darts. -/
noncomputable def CombinatorialMap.toGMap2 {D : Type u} [Fintype D] [DecidableEq D]
    (M : CombinatorialMap D) : GMap2 (D × Bool) :=
  sorry

/-- A hypermap in the three-permutation presentation. -/
structure Hypermap (D : Type u) [Fintype D] [DecidableEq D] where
  sigma : Equiv.Perm D
  phi : Equiv.Perm D
  alpha : Equiv.Perm D
  comp : sigma * phi * alpha = 1

/-- Conversion from a hypermap to the generalized-map hub. -/
noncomputable def Hypermap.toGMap2 {D : Type u} [Fintype D] [DecidableEq D]
    (H : Hypermap D) : GMap2 (D × Bool) :=
  sorry

/-- Polygonal schemas are bundled because relabelling and cancellation change the label
type. Surface validity is a separate predicate; do not hide it in an unconstrained field. -/
structure PolygonalSchema where
  label : Type u
  fintypeLabel : Fintype label
  decEqLabel : DecidableEq label
  faces : List (CyclicWord (label × Bool))

/-!
`Cellulation2` should be compiled only after its side-incidence representation is pinned.
It is not merely an incidence poset: the roadmap requires a concrete counterexample of
two non-isomorphic cellulations with the same incidence poset.

The six comparison theorems are central targets, but most wait on the realization and
subdivision APIs. Representative forms are:

  -- After canonical subdivision, the generalized-map flag complex agrees with the
  -- barycentric subdivision of a combinatorial surface.
  theorem flagComplex_toGMap2 ... : ...

  theorem realization_homeomorph_flagComplex ... : ...
  theorem toCellulation_toGMap2 ... : ...
  theorem toGMap2_toCombinatorialMap ... : ...
  theorem dual_dual ... : ...
  theorem schema_conversion_recovers_gluings ... : ...
-/

/-! ## Layer 3: realization -/

/-- Direct topological realization of a generalized map as triangles modulo side gluings.
It is intentionally defined for every generalized map, before imposing the surface
condition, and not through an abstract simplicial complex. -/
noncomputable def GMap2.realization {D : Type u} [Fintype D] [DecidableEq D]
    (G : GMap2 D) : Type u :=
  sorry

/-- The quotient realization carries its quotient topology. -/
noncomputable instance GMap2.realizationTopologicalSpace
    {D : Type u} [Fintype D] [DecidableEq D] (G : GMap2 D) :
    TopologicalSpace G.realization :=
  sorry

/-- The direct realization of a finite generalized map is compact. -/
instance GMap2.realizationCompactSpace
    {D : Type u} [Fintype D] [DecidableEq D] (G : GMap2 D) :
    CompactSpace G.realization :=
  sorry

/-!
Once `IsSurfaceGMap` and the simplicial subdivision bridge exist, add the decisive
milestones:

  theorem IsSurfaceGMap.realization_isSurface ...
  theorem IsSurfaceGMap.eulerChar_eq ...
  theorem flagComplex_isSimplicial_of_subdivided ...
  theorem realization_homeomorph_flagComplex ...
  theorem exists_gmap_of_compactSurface ...

The projective-plane `aa` map must remain an explicit counter-witness to defining
realization through the unsubdivided flag complex.
-/

/-! ## Layer 4: operations on finite surfaces -/

/-- Edge subdivision changes the dart type, hence returns a bundled map. -/
noncomputable def GMap2.subdivideEdge {D : Type u} [Fintype D] [DecidableEq D]
    (G : GMap2 D) (e : G.Cell 1) : BundledGMap2 :=
  sorry

/-- Face subdivision likewise changes the dart type. -/
noncomputable def GMap2.subdivideFace {D : Type u} [Fintype D] [DecidableEq D]
    (G : GMap2 D) (f : G.Cell 2) : BundledGMap2 :=
  sorry

/-- Ordinary duality reverses the three adjacencies. It is defined combinatorially for
all maps; preservation of the chosen surface-with-boundary convention is asserted only
under the appropriate closedness hypothesis. -/
noncomputable def GMap2.dual {D : Type u} [Fintype D] [DecidableEq D]
    (G : GMap2 D) : GMap2 D :=
  sorry

/-- The orientation double cover has two sheets indexed by `Bool`. -/
noncomputable def GMap2.orientationDoubleCover
    {D : Type u} [Fintype D] [DecidableEq D] (G : GMap2 D) : GMap2 (D × Bool) :=
  sorry

/-- Capping all boundary circles may change the dart type. -/
noncomputable def GMap2.cap {D : Type u} [Fintype D] [DecidableEq D]
    (G : GMap2 D) : BundledGMap2 :=
  sorry

/-- Doubling along the boundary uses two copies of the dart set. -/
noncomputable def GMap2.double {D : Type u} [Fintype D] [DecidableEq D]
    (G : GMap2 D) : GMap2 (D × Bool) :=
  sorry

/-- Connected sum is another index-changing operation. -/
noncomputable def GMap2.connectedSum
    {D : Type u} {E : Type v}
    [Fintype D] [DecidableEq D] [Fintype E] [DecidableEq E]
    (G : GMap2 D) (H : GMap2 E) : BundledGMap2 :=
  sorry

/-!
Admissible edge contraction and cutting along a combinatorial curve should be compiled
only after `IsContractible` and `CombinatorialCurve` are real predicates/types. Their
realization theorems, not merely orbit-count identities, are the milestones.

Likewise add the precise covering theorem for `orientationDoubleCover`, including the
boundary behaviour, and the Euler-characteristic/orientability/connectedness formulas for
capping and doubling.
-/

/-! ## Layer 5: embedded graphs and the Heffter--Edmonds--Ringel correspondence -/

/-!
The README explicitly requires verification of Mathlib's current multigraph `Graph α β`
API before this layer. Until that check is done, do not create a private graph synonym
merely to make the targets parse. Once verified, pin:

  def GMap2.underlyingGraph ...
  structure GraphEmbedding ...
  def GraphEmbedding.IsCellular : Prop := ...
  def RotationSystem ...
  def SignedRotationSystem ...

  theorem cellularEmbeddings_equiv_gmaps ...
  theorem orientedCellularEmbeddings_equiv_rotationSystems ...
  theorem cellularEmbeddings_equiv_signedRotationSystems ...
  theorem vertexCount_sub_edgeCount_add_faceCount_eq_eulerChar ...

The cellularity hypothesis is essential and should have the torus/non-disc-face
counterexample beside the implementation.
-/

/-! ## Layer 6: polygonal schemas and normal forms -/

/-!
Once `PolygonalSchema.IsSurface`, schema relabelling, and the isomorphism closure are
concrete, compile the elementary move relation and the two headline targets:

  theorem closedSchema_reduces_to_normalForm ...
  theorem closedSchema_reduces_to_normalForm_rel_caps ...
  theorem SchemaMove.realization_homeomorph ...

The relative theorem preserving distinguished cap faces is not optional bookkeeping: it
is what makes classification with boundary reduce cleanly to the closed case.
-/

/-! ## Layer 7: cellulation homology and the edge-path group -/

/-!
This layer waits on `Cellulation2`. When that presentation is pinned, representative
targets should include the finite chain complex, `d ∘ d = 0`, Euler--Poincaré, the
combinatorial edge-path-group presentation, abelianization, subdivision invariance, and
the two normal-form computations. Use the PID structure theorem for the rectangular
boundary matrices; do not route through the current square-matrix Smith-normal-form file.

Keep the names presentation-specific (`Cellulation2.homology`,
`Cellulation2.edgePathGroup`) until comparison with singular homology / topological `π₁`
actually exists.
-/

/-! ## Layer 8: classification of compact surfaces -/

/-- The standard connected compact surfaces, including boundary. -/
inductive StandardSurface where
  | orientable (g : ℕ) (b : ℕ)
  | nonorientable (k : ℕ) (hk : 0 < k) (b : ℕ)

/-- A topological model of each standard surface. The concrete models are fixed by the
implementation, not by the classification theorem. -/
noncomputable def StandardSurface.model : StandardSurface → Type :=
  sorry

/-- Euler characteristic of the standard model. -/
def StandardSurface.eulerChar : StandardSurface → ℤ
  | .orientable g b => 2 - 2 * (g : ℤ) - (b : ℤ)
  | .nonorientable k _ b => 2 - (k : ℤ) - (b : ℤ)

/-!
Once the shared surface classes and boundary-component API exist, compile the library
statements rather than a quotient-of-presentations surrogate:

  theorem exists_standard_homeomorph ...
  theorem standard_homeomorph_unique ...
  theorem classification_of_surfaces ... : ∃! S : StandardSurface, ...
  theorem homeomorph_iff_invariants ...
  theorem exists_closed_minus_discs ...

Uniqueness must use Euler characteristic, orientability, and boundary-component count;
the boundary count is topological only after `PlanarTopology` supplies two-dimensional
invariance of domain.
-/

/-! ## Follow-on layer 9: curves, cutting, and mapping class groups -/

/-!
This layer should consume the actual topological/PL isotopy and surface vocabulary rather
than prototype private replacements. Once those types exist, pin the full and
orientation-preserving mapping-class groups, relative-boundary base cases, Dehn twists,
the change-of-coordinates principle, and the torus computations.

For the Dehn--Lickorish result, prefer two functional theorem targets rather than one
eponymous conjunction:

  -- All Dehn twists generate the positive mapping-class group.
  theorem dehnTwist_closure_eq_top ...

  -- Lickorish's explicit `3g - 1` finite generating set.
  theorem exists_dehnTwist_generatingSet_card_eq_three_mul_genus_sub_one ...

The prose/docstrings should still call these the Dehn--Lickorish theorem.
-/

/-! ## Follow-on layer 10: planarity -/

/-!
This theorem suite waits on the verified common multigraph/embedding API from layer 5.
When that vocabulary is available, use descriptive Lean names and keep the historical
names in docstrings. The intended representative targets are:

  /-- Tutte's Wheel Theorem. -/
  theorem <wheel-reduction name after the exact statement is pinned> ...

  /-- Kuratowski's Theorem. -/
  theorem isPlanar_iff_no_K5_K33_topologicalMinor ...

  /-- Wagner's Theorem. -/
  theorem isPlanar_iff_no_K5_K33_minor ...

  /-- Tutte's Peripheral Cycle Theorem. -/
  theorem isPeripheral_iff_isFacial ...

  /-- Whitney's Unique Embedding Theorem. -/
  theorem planeEmbedding_unique_up_to_equivalence ...

  /-- Whitney's 2-Isomorphism Theorem. -/
  theorem cycleMatroid_iso_iff_twoIsomorphic ...

  def Graph.cycleSpace ...
  def Graph.cutSpace ...
  theorem cycleSpace_finrank ...
  theorem cycleSpace_orthogonal_cutSpace ...
  theorem planar_dual_cycleSpace_eq_cutSpace ...

  -- A 2-basis means that each edge occurs in at most two basis cycles. Pin the exact
  -- finite-support expression against the eventual cycle-space representation.
  def Graph.HasTwoBasis ...

  /-- Mac Lane's Planarity Criterion. -/
  theorem isPlanar_iff_hasTwoBasis ...

  /-- Fáry's Theorem. -/
  theorem exists_straightLine_planeEmbedding ...

  /-- Tutte's Spring Embedding Theorem. -/
  theorem exists_convex_planeEmbedding ...

  /-- The Five Colour Theorem. -/
  theorem colorable_five_of_isPlanar ...

The exact wheel and Whitney-2-isomorphism signatures should be named only after their
statements are fully expanded; the README currently leaves the former schematic and the
latter as `...`, so this file should not pretend otherwise.
-/

end TauCetiRoadmap.SurfaceTopology
